use_frameworks!

platform :ios, '8.0'

target 'LCSelectCountryCode_Example' do
  pod 'LCSelectCountryCode', :path => '../'

  target 'LCSelectCountryCode_Tests' do
    inherit! :search_paths

    
  end
end
